import {
  FaChartLine,
  FaCashRegister,
  FaUsers,
  FaWarehouse,
  FaFileInvoiceDollar,
  FaHandshake,
  FaShoppingCart,
  FaUserTie,
  FaBalanceScale,
  FaFileContract,
  FaPiggyBank,
  FaClipboardList,
  FaDollarSign,
  FaRegBuilding,
  FaMoneyCheckAlt,
  FaTruck,
  FaLandmark,
  FaSearchDollar,
  FaTags,
  FaUser,
} from "react-icons/fa";

import {
  MdDashboard,
  MdInventory,
  MdOutlineSavings,
  MdOutlinePolicy,
  MdOutlineReceipt,
  MdEventNote,
  MdAttachMoney,
  MdOutlineReport,
  MdLocalShipping,
  MdStore,
  MdSupervisorAccount,
} from "react-icons/md";

import {
  AiOutlineFileDone,
  AiOutlineAudit,
  AiOutlineBarChart,
  AiOutlineBank,
  AiOutlineSchedule,
} from "react-icons/ai";

import {
  IoMdBusiness,
  IoMdStats,
  IoMdWallet,
  IoMdCart,
  IoIosList,
  IoIosPricetags,
  IoIosSettings,
} from "react-icons/io";
import { IconType } from "react-icons";

export const iconsDictionary: {
  [key: string]: { name: string; component: IconType };
} = {
  dashboard: { name: "Dashboard", component: MdDashboard },
  sales: { name: "Sales", component: FaChartLine },
  inventory: { name: "Inventory", component: MdInventory },
  customers: { name: "Customers", component: FaUsers },
  suppliers: { name: "Suppliers", component: FaHandshake },
  products: { name: "Products", component: FaShoppingCart },
  invoices: { name: "Invoices", component: FaFileInvoiceDollar },
  contracts: { name: "Contracts", component: FaFileContract },
  payments: { name: "Payments", component: FaDollarSign },
  cashRegister: { name: "Cash Register", component: FaCashRegister },
  savings: { name: "Savings", component: MdOutlineSavings },
  accounts: { name: "Accounts", component: IoMdWallet },
  audit: { name: "Audit", component: AiOutlineAudit },
  reports: { name: "Reports", component: AiOutlineFileDone },
  fiscalPolicies: { name: "Fiscal Policies", component: MdOutlinePolicy },
  taxReturn: { name: "Tax Return", component: AiOutlineBarChart },
  logistics: { name: "Logistics", component: FaTruck },
  company: { name: "Company", component: FaRegBuilding },
  compliance: { name: "Compliance", component: FaBalanceScale },
  notifications: { name: "Notifications", component: MdEventNote },
  userManagement: { name: "User Management", component: MdSupervisorAccount },
  receipts: { name: "Receipts", component: MdOutlineReceipt },
  transactions: { name: "Transactions", component: FaMoneyCheckAlt },
  bank: { name: "Bank", component: AiOutlineBank },
  taxManagement: { name: "Tax Management", component: IoMdBusiness },
  warehouse: { name: "Warehouse", component: FaWarehouse },
  budgets: { name: "Budgets", component: FaPiggyBank },
  store: { name: "Store", component: MdStore },
  priceTags: { name: "Price Tags", component: IoIosPricetags },
  schedule: { name: "Schedule", component: AiOutlineSchedule },
  reportsOverview: { name: "Reports Overview", component: IoMdStats },
  tasks: { name: "Tasks", component: FaClipboardList },
  searchFinance: { name: "Search Finance", component: FaSearchDollar },
  events: { name: "Events", component: MdEventNote },
  policy: { name: "Policy", component: MdOutlinePolicy },
  legal: { name: "Legal", component: FaLandmark },
  orders: { name: "Orders", component: IoIosList },
  tags: { name: "Tags", component: FaTags },
  user: { name: "User", component: FaUser },
  settings: { name: "Settings", component: IoIosSettings },
  userTie: { name: "userTie", component: FaUserTie },
  attachMoney: { name: "attachMoney", component: MdAttachMoney },
  outlineReport: { name: "outlineReport", component: MdOutlineReport },
  localShipping: { name: "localShipping", component: MdLocalShipping },
  cart: { name: "cart", component: IoMdCart },
};
